name: ci-cd

on: 
  push:
    branches: [ master ]

jobs:
  # scan-iac:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run Snyk to check terraform files for security issues
  #       uses: snyk/actions/iac@master
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
  #       continue-on-error: true
  #       with:
  #         args: --sarif-file-output=snyk_iac.sarif > snyk_iac.txt
  #     - name: Upload result to GitHub Code Scanning
  #       uses: github/codeql-action/upload-sarif@v2
  #       with:
  #         sarif_file: snyk_iac.sarif
  #     - name: Archive results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: report
  #         path: snyk_iac.sarif
  #     - name: Fail pipeline if finding with severity high found
  #       run: |
  #         if grep -q '[High]' snyk_iac.txt || grep -q '[Critical]' snyk_iac.txt; then
  #           echo "found!"
  #           exit 1
  #         fi
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: OWASP ZAP
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: "http://testphp.vulnweb.com/"
          fail_action: false
      - name: Fail pipeline if finding with severity high found
        run: 
          sudo apt-get install unzip
          unzip zap-scan
          if ! grep -q '| High | 0 |' report_md.md; then
            echo "found!"
            exit 1
          fi
