name: test-cost

on: push

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    env:
      TF_ROOT: terraform/module
    steps: 
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Checkout base branch
        uses: actions/checkout@v3
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${TF_ROOT} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: /tmp/infracost-base.json